package com.spring.rest.crud.model;
// Generated Feb 18, 2019 3:40:54 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Alergias generated by hbm2java
 */

@Entity
@Table(name="alergias")
public class Alergias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -121776549674418931L;
	
	@Id
	@GeneratedValue
	private Integer id_alergia;
	
	private String nombre;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yy")
	private Date fecha_alta;
	private String medicamento;
	@ManyToMany(
			fetch = FetchType.EAGER,
			mappedBy = "alergias"
			)
	@JsonIgnore
	private Set<Usuarios> usuarios = new HashSet(0);

	public Alergias() {
	}

	public Alergias(String nombre) {
		this.nombre = nombre;
	}

	public Alergias(String nombre, Date fechaAlta, String medicamento, Set<Usuarios> usuarios) {
		this.nombre = nombre;
		this.fecha_alta = fechaAlta;
		this.medicamento = medicamento;
		this.usuarios = usuarios;
	}

	public Integer getId_alergia() {
		return id_alergia;
	}

	public void setId_alergia(Integer id_alergia) {
		this.id_alergia = id_alergia;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFecha_alta() {
		return fecha_alta;
	}

	public void setFecha_alta(Date fecha_alta) {
		this.fecha_alta = fecha_alta;
	}

	public String getMedicamento() {
		return medicamento;
	}

	public void setMedicamento(String medicamento) {
		this.medicamento = medicamento;
	}

	public Set<Usuarios> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(Set<Usuarios> usuarios) {
		this.usuarios = usuarios;
	}

}
