package com.spring.rest.crud.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.JoinColumn;

/**
 * Recetas generated by hbm2java
 */

@Entity
@Table(name="recetas")
public class Recetas implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	private Integer id_receta;
	
	private Integer folio_receta;
	private String medico;
	private String medicamento;
	@ManyToMany(
			fetch = FetchType.EAGER,
			mappedBy = "recetas"
			)
	@JsonIgnore
	private Set<Usuarios> usuarios = new HashSet(0);
	
	public Recetas() {
	}
	
	public Recetas(Integer folio_receta) {
		this.folio_receta = folio_receta;
	}
	
	public Recetas(String medico, String medicamento) {
		this.medico = medico;
		this.medicamento = medicamento;
	}
	
	
	public Recetas(Integer folio_receta, String medico, String medicamento, Set<Usuarios> usuarios) {
		this.folio_receta = folio_receta;
		this.medico = medico;
		this.medicamento = medicamento;
		this.usuarios = usuarios;
	}
	
	public Integer getId_receta() {
		return id_receta;
	}
	
	public void setId_receta(Integer id_receta) {
		this.id_receta = id_receta;
	}
	
	public Integer getFolio_receta() {
		return folio_receta;
	}
	
	public void setFolio_receta(Integer folio_receta) {
		this.folio_receta = folio_receta;
	}
	
	public String getMedico() {
		return medico;
	}
	
	public void setMedico(String medico) {
		this.medico = medico;
	}
	
	public String getMedicamento() {
		return medicamento;
	}
	
	public void setMedicamento(String medicamento) {
		this.medicamento = medicamento;
	}
	
	
	public Set<Usuarios> getUsuarios(){
		return usuarios;
	}
	
	public void setUsuarios (Set<Usuarios> usuarios) {
		this.usuarios = usuarios;
	}
}






